alias stash="git stash -m "
alias pop="git stash pop"
alias drop="git stash drop"
#alias graph="git log --graph --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%an%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)- %s%C(reset)' "
alias graph="git log --graph --oneline --decorate"
alias gst="git status"
alias add="git add"
alias a="add"
alias commit="git commit"
alias ammend="git commit --amend --no-edit"
alias commitm="git commit -m"
alias c="commit"
alias cn="c --no-verify"
alias clone="git clone"
alias wb="git worktree -b"
alias s="git status"
alias grs="git restore"
alias grst="git restore --staged"
alias gupa="git pull --rebase --autostash"
alias gp="git push"
alias gpn="git push --no-verify"
alias gpf="git push --force-with-lease"
alias glog="graph"
alias gcm="git checkout main"
alias gco="git checkout"
alias gcb="git checkout -b"
alias update-all="~/.config/scripts/git/run_git_command_in_repos.sh \"git pull --rebase --autostash\""
alias commitsearch="~/.config/scripts/git/search_commits.sh"
alias repobranches="~/.config/scripts/git/list_repo_branches.sh"

unalias gwta
gwta() {
    git worktree add "$1" "$2" && cd "$1"
}

