alias stash="git stash -m "
alias pop="git stash pop"
alias drop="git stash drop"
alias graph='git log --graph --abbrev-commit --decorate --format=format:'\''%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n'\'\''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'\'' --all'
alias gst="git status"
alias grs="git restore --staged ."
alias gr="git restore ."
alias add="git add ."
alias commit="git commit"
alias ammend="git commit --amend --no-edit"
alias commitm="git commit -m"
alias clone="git clone"
alias wb="git worktree -b"
alias glog="glod"
